const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const KEY='civilMediaDataV1', AUTH='civilMediaAuthV1';
const fallbackImg='https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=1200&q=80';

const seedArticles = [
  {id:'a1',titleEn:'Bhaktapur launches new digital public service initiative',titleNp:'भक्तपुरमा नयाँ डिजिटल सार्वजनिक सेवा पहल सुरु',excerptEn:'Local services are moving online with a new citizen-focused digital program.',excerptNp:'नागरिक केन्द्रित नयाँ डिजिटल कार्यक्रममार्फत स्थानीय सेवाहरू अनलाइन हुँदैछन्।',category:'Nepal',author:'Civil Media Desk',date:'2026-09-19T08:30',status:'published',breaking:true,image:'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80',contentEn:'Bhaktapur has introduced a new digital public-service initiative designed to make common municipal services easier to access.\n\nThe program includes online information, service-request tracking and a unified help desk. Officials said the rollout will be expanded after an initial public feedback period.',contentNp:'भक्तपुरमा सामान्य नगरपालिका सेवाहरू पहुँचयोग्य बनाउन नयाँ डिजिटल सार्वजनिक सेवा पहल सुरु गरिएको छ।\n\nकार्यक्रममा अनलाइन सूचना, सेवा अनुरोध ट्र्याकिङ र एकीकृत सहायता डेस्क समावेश छ। प्रारम्भिक सार्वजनिक प्रतिक्रियापछि सेवा विस्तार गरिने बताइएको छ.'},
  {id:'a2',titleEn:'Parliament session focuses on economic priorities',titleNp:'संसद् बैठकमा आर्थिक प्राथमिकतामाथि केन्द्रित छलफल',excerptEn:'Lawmakers discussed budget implementation, jobs and infrastructure priorities.',excerptNp:'सांसदहरूले बजेट कार्यान्वयन, रोजगारी र पूर्वाधार प्राथमिकताबारे छलफल गरे।',category:'Politics',author:'Anita Shrestha',date:'2026-09-19T07:10',status:'published',breaking:true,image:'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=1200&q=80',contentEn:'Lawmakers used the session to debate implementation priorities for the national budget, including employment, infrastructure and service delivery.\n\nDifferent parties presented their own approaches to sequencing public spending and oversight.',contentNp:'सांसदहरूले राष्ट्रिय बजेट कार्यान्वयन, रोजगारी, पूर्वाधार र सेवा प्रवाहका प्राथमिकताबारे छलफल गरे।\n\nविभिन्न दलहरूले सार्वजनिक खर्च र अनुगमनलाई कसरी अघि बढाउने भन्नेबारे आ-आफ्ना धारणा राखे.'},
  {id:'a3',titleEn:'Nepal businesses expand digital payments',titleNp:'नेपालका व्यवसायमा डिजिटल भुक्तानीको विस्तार',excerptEn:'Merchants are adopting QR and mobile payments across urban and regional markets.',excerptNp:'शहरी र क्षेत्रीय बजारमा व्यापारीहरूले QR र मोबाइल भुक्तानी अपनाइरहेका छन्।',category:'Business',author:'Rajan Karki',date:'2026-09-18T18:20',status:'published',breaking:false,image:'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&q=80',contentEn:'Digital payment tools are becoming more common among small and mid-sized businesses. Merchants cite faster settlement and customer convenience as key reasons for adoption.',contentNp:'साना तथा मझौला व्यवसायमा डिजिटल भुक्तानी साधनको प्रयोग बढ्दै गएको छ। व्यापारीहरूले छिटो कारोबार र ग्राहकको सहजतालाई मुख्य कारण बताएका छन्.'},
  {id:'a4',titleEn:'Regional leaders meet for climate and trade talks',titleNp:'जलवायु र व्यापारबारे क्षेत्रीय नेताहरूको बैठक',excerptEn:'Officials discussed climate resilience, trade links and regional cooperation.',excerptNp:'अधिकारीहरूले जलवायु सहनशीलता, व्यापारिक सम्बन्ध र क्षेत्रीय सहकार्यबारे छलफल गरे।',category:'World',author:'International Desk',date:'2026-09-18T15:05',status:'published',breaking:false,image:'https://images.unsplash.com/photo-1521295121783-8a321d551ad2?auto=format&fit=crop&w=1200&q=80',contentEn:'Regional leaders met to discuss climate adaptation, trade facilitation and cross-border infrastructure. The meeting concluded with a joint statement outlining areas for technical cooperation.',contentNp:'क्षेत्रीय नेताहरूले जलवायु अनुकूलन, व्यापार सहजीकरण र सीमापार पूर्वाधारबारे छलफल गरे। बैठकले प्राविधिक सहकार्यका क्षेत्र उल्लेख गरिएको संयुक्त वक्तव्य जारी गर्‍यो.'},
  {id:'a5',titleEn:'National football league draws strong crowds',titleNp:'राष्ट्रिय फुटबल लिगमा दर्शकको उत्साह',excerptEn:'Weekend fixtures brought packed stands and close matches.',excerptNp:'सप्ताहन्तका खेलमा भरिभराउ दर्शक र प्रतिस्पर्धात्मक खेल देखिए।',category:'Sports',author:'Sports Desk',date:'2026-09-18T11:30',status:'published',breaking:false,image:'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=1200&q=80',contentEn:'The latest league round featured close contests and strong attendance. Clubs are now preparing for a busy stretch of fixtures over the coming weeks.',contentNp:'लिगको पछिल्लो चरणमा प्रतिस्पर्धात्मक खेल र उल्लेख्य दर्शक उपस्थिति देखियो। क्लबहरू आगामी हप्ताका व्यस्त खेलतालिकाको तयारीमा छन्.'},
  {id:'a6',titleEn:'New Nepali film opens to positive early response',titleNp:'नयाँ नेपाली फिल्मप्रति प्रारम्भिक सकारात्मक प्रतिक्रिया',excerptEn:'Audiences praised the film’s performances and visual storytelling.',excerptNp:'दर्शकहरूले अभिनय र दृश्य कथनको प्रशंसा गरेका छन्।',category:'Entertainment',author:'Culture Desk',date:'2026-09-17T19:10',status:'published',breaking:false,image:'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80',contentEn:'A new Nepali feature film opened this week, with early audiences highlighting its performances, music and cinematography.',contentNp:'यस हप्ता प्रदर्शनमा आएको नयाँ नेपाली फिल्मको अभिनय, संगीत र छायांकनलाई प्रारम्भिक दर्शकहरूले सकारात्मक प्रतिक्रिया दिएका छन्.'},
  {id:'a7',titleEn:'Local startups build tools with artificial intelligence',titleNp:'स्थानीय स्टार्टअपले एआई आधारित उपकरण निर्माण गर्दै',excerptEn:'Teams are applying AI to education, commerce and productivity tools.',excerptNp:'टोलीहरूले शिक्षा, वाणिज्य र उत्पादकता उपकरणमा एआई प्रयोग गरिरहेका छन्।',category:'Technology',author:'Tech Desk',date:'2026-09-17T14:35',status:'published',breaking:false,image:'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',contentEn:'A growing group of local startups is experimenting with artificial intelligence for education, commerce and workplace tools. Founders say affordability and local-language support remain important design goals.',contentNp:'स्थानीय स्टार्टअपहरूले शिक्षा, वाणिज्य र कार्यस्थलका उपकरणमा कृत्रिम बुद्धिमत्ता प्रयोग गर्न थालेका छन्। संस्थापकहरूका अनुसार किफायती सेवा र स्थानीय भाषाको समर्थन मुख्य प्राथमिकता हुन्.'},
  {id:'a8',titleEn:'Photo story: Morning life around Bhaktapur Durbar Square',titleNp:'फोटो कथा: भक्तपुर दरबार क्षेत्रमा बिहानको जीवन',excerptEn:'A visual look at the city as markets and courtyards come alive.',excerptNp:'बजार र चोकहरू जाग्दै गर्दा शहरको दृश्य यात्रा।',category:'Gallery',author:'Photo Desk',date:'2026-09-16T09:00',status:'published',breaking:false,image:'https://images.unsplash.com/photo-1571401835393-8c5f35328320?auto=format&fit=crop&w=1200&q=80',contentEn:'This photo story follows the rhythm of morning life around Bhaktapur, from tea stalls and temple courtyards to the first wave of commuters.',contentNp:'यो फोटो कथाले भक्तपुरको बिहानको लय पछ्याउँछ—चिया पसल, मन्दिरका चोक र बिहानैका यात्रुसम्म.'}
];

const defaultData={
  settings:{company:'The Civil Media Private Limited',tagline:'Independent • Accurate • Responsible',address:'Bhaktapur, Nepal',email:'news@thecivilmedia.com',phone:'+977 01-0000000',logo:'assets/logo.jpeg',brand:'#071a7a',accent:'#d71920',bodyFont:'Inter',headingFont:'Playfair Display',radius:'16',layout:'classic',facebook:'',youtube:'',instagram:'',x:''},
  credentials:null,
  articles:seedArticles,
  ads:[
    {id:'ad1',name:'Header Banner',placement:'header',label:'Advertisement',dimensions:'728 × 90',image:'',url:'',alt:'',enabled:true},
    {id:'ad2',name:'Sidebar Rectangle',placement:'sidebar',label:'Advertisement',dimensions:'300 × 250',image:'',url:'',alt:'',enabled:true},
    {id:'ad3',name:'Footer Banner',placement:'footer',label:'Advertisement',dimensions:'728 × 90',image:'',url:'',alt:'',enabled:true}
  ],
  subscribers:[],messages:[]
};
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(defaultData)}catch{return structuredClone(defaultData)}}
let data=load();
if(!Array.isArray(data.ads)) data.ads=structuredClone(defaultData.ads);
// Remove the old prototype credentials so the admin account is created explicitly on first use.
if(data.credentials?.username==='admin' && data.credentials?.password==='admin123'){data.credentials=null;localStorage.setItem(KEY,JSON.stringify(data))}
let lang=localStorage.getItem('civilLang')||'en';
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

function safeUrl(v=''){const value=String(v||'').trim();if(!value)return '';if(/^https?:\/\//i.test(value))return value;if(/^mailto:/i.test(value)||/^tel:/i.test(value))return value;return 'https://'+value}
function socialAnchor(label,url){const href=safeUrl(url);return href?`<a href="${esc(href)}" target="_blank" rel="noopener noreferrer">${label}</a>`:''}
function adByPlacement(placement){return (data.ads||[]).find(a=>a.enabled&&a.placement===placement)}
function publicAd(placement, fallback='Advertisement'){const a=adByPlacement(placement);if(!a)return '';const label=esc(a.label||fallback),dim=esc(a.dimensions||'');const inner=a.image?`<img src="${esc(a.image)}" alt="${esc(a.alt||a.name||'Advertisement')}">`:`<div><strong>${label}</strong>${dim?esc(dim):''}</div>`;return `<div class="ad managed-ad ad-${esc(placement)}">${a.url?`<a href="${esc(safeUrl(a.url))}" target="_blank" rel="noopener noreferrer" aria-label="${esc(a.name||'Advertisement')}">${inner}</a>`:inner}</div>`}
function articleTitle(a){return lang==='np'?(a.titleNp||a.titleEn):(a.titleEn||a.titleNp)}
function articleExcerpt(a){return lang==='np'?(a.excerptNp||a.excerptEn):(a.excerptEn||a.excerptNp)}
function articleContent(a){return lang==='np'?(a.contentNp||a.contentEn):(a.contentEn||a.contentNp)}
const bs2083Months=[
  {m:1,en:'Baisakh',np:'बैशाख',start:'2026-04-14',days:31},
  {m:2,en:'Jestha',np:'जेठ',start:'2026-05-15',days:31},
  {m:3,en:'Asar',np:'असार',start:'2026-06-15',days:32},
  {m:4,en:'Shrawan',np:'साउन',start:'2026-07-17',days:31},
  {m:5,en:'Bhadra',np:'भदौ',start:'2026-08-17',days:31},
  {m:6,en:'Asoj',np:'असोज',start:'2026-09-17',days:31},
  {m:7,en:'Kartik',np:'कात्तिक',start:'2026-10-18',days:30},
  {m:8,en:'Mangsir',np:'मंसिर',start:'2026-11-17',days:29},
  {m:9,en:'Poush',np:'पुस',start:'2026-12-16',days:30},
  {m:10,en:'Magh',np:'माघ',start:'2027-01-15',days:29},
  {m:11,en:'Falgun',np:'फागुन',start:'2027-02-13',days:30},
  {m:12,en:'Chaitra',np:'चैत',start:'2027-03-15',days:30}
];
function toNepaliDigits(v){return String(v).replace(/[0-9]/g,d=>'०१२३४५६७८९'[d])}
function bsDate(v){
  const d=new Date(v); if(Number.isNaN(d.getTime())) return '';
  const iso=d.toISOString().slice(0,10);
  const start=new Date('2026-04-14T00:00:00Z'), end=new Date('2027-04-13T23:59:59Z');
  if(d<start||d>end) return '';
  let month=bs2083Months[0];
  for(const x of bs2083Months){ if(new Date(x.start+'T00:00:00Z')<=d) month=x; else break; }
  const day=Math.floor((d-new Date(month.start+'T00:00:00Z'))/86400000)+1;
  return lang==='np'?`${month.np} ${toNepaliDigits(day)}, ${toNepaliDigits(2083)}`:`${month.en} ${day}, 2083 BS`;
}
function dateFmt(v){const ad=new Intl.DateTimeFormat(lang==='np'?'ne-NP':'en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));const bs=bsDate(v);return bs?`${ad} <span class=\"bs-date\">• ${esc(bs)}</span>`:ad}
function todayNepali(){const bs=bsDate(new Date());return bs?`<span class=\"today-bs\">🇳🇵 ${esc(bs)}</span>`:''}

const labels={en:{latest:'Latest News',nepal:'Nepal',politics:'Politics',business:'Business',world:'International',sports:'Sports',entertainment:'Entertainment',technology:'Technology',gallery:'Video / Photo',search:'Search',breaking:'BREAKING',read:'Read more',newsletter:'Get the top stories in your inbox',newsletterSub:'Subscribe for a concise daily briefing from The Civil Media.',subscribe:'Subscribe',trending:'Trending',about:'About The Civil Media',contact:'Contact',home:'Home',allNews:'All News'},np:{latest:'ताजा समाचार',nepal:'नेपाल',politics:'राजनीति',business:'व्यवसाय',world:'अन्तर्राष्ट्रिय',sports:'खेलकुद',entertainment:'मनोरञ्जन',technology:'प्रविधि',gallery:'भिडियो / फोटो',search:'खोज्नुहोस्',breaking:'ब्रेकिङ',read:'पूरा पढ्नुहोस्',newsletter:'मुख्य समाचार इमेलमा पाउनुहोस्',newsletterSub:'द सिभिल मिडियाबाट दैनिक संक्षिप्त समाचार अपडेट प्राप्त गर्नुहोस्।',subscribe:'सदस्य बन्नुहोस्',trending:'चर्चित',about:'द सिभिल मिडियाबारे',contact:'सम्पर्क',home:'गृहपृष्ठ',allNews:'सबै समाचार'}};
function L(k){return labels[lang][k]||k}
function applyTheme(){const s=data.settings;document.documentElement.style.setProperty('--brand',s.brand);document.documentElement.style.setProperty('--accent',s.accent);document.documentElement.style.setProperty('--radius',`${s.radius||16}px`);document.documentElement.style.setProperty('--font-body',`${s.bodyFont||'Inter'}, "Noto Sans Devanagari", sans-serif`);document.documentElement.style.setProperty('--font-heading',`${s.headingFont||'Playfair Display'}, "Noto Sans Devanagari", serif`)}
function published(){return data.articles.filter(a=>a.status==='published').sort((a,b)=>new Date(b.date)-new Date(a.date))}
function card(a){return `<article class="card"><a href="#article/${a.id}"><img src="${esc(a.image||fallbackImg)}" alt="${esc(articleTitle(a))}" onerror="this.src='${fallbackImg}'"></a><div class="body"><span class="eyebrow">${esc(a.category)}</span><a href="#article/${a.id}"><h3>${esc(articleTitle(a))}</h3></a><div class="meta"><span>🕐 ${dateFmt(a.date)}</span><span>✍️ ${esc(a.author)}</span></div><p>${esc(articleExcerpt(a))}</p><a href="#article/${a.id}" style="color:var(--brand);font-weight:800">${L('read')} →</a></div></article>`}
function listItem(a){return `<article class="list-item"><a href="#article/${a.id}"><img src="${esc(a.image||fallbackImg)}" alt=""></a><div class="body"><span class="eyebrow">${esc(a.category)}</span><a href="#article/${a.id}"><h3>${esc(articleTitle(a))}</h3></a><div class="meta"><span>🕐 ${dateFmt(a.date)}</span><span>✍️ ${esc(a.author)}</span></div></div></article>`}
function publicHeader(active=''){const s=data.settings;return `<div class="topline"><div class="container"><span>📍 ${esc(s.address)} &nbsp; • &nbsp; ${new Date().toLocaleDateString(lang==='np'?'ne-NP':'en-GB',{weekday:'long',year:'numeric',month:'long',day:'numeric'})} ${todayNepali()}</span><div class="socials">${socialAnchor('Facebook',s.facebook)}${socialAnchor('YouTube',s.youtube)}${socialAnchor('Instagram',s.instagram)}${socialAnchor('X',s.x)}</div></div></div><header class="brandbar"><div class="container"><a class="brand" href="#home"><img src="${esc(s.logo)}" alt="logo"><div><h1>${esc(s.company)}</h1><small>${esc(s.tagline)}</small></div></a><div class="ad-slot" style="min-height:72px;width:360px">${publicAd('header')}</div><div class="header-actions"><button class="btn secondary" onclick="setLang('${lang==='en'?'np':'en'}')">🌐 ${lang==='en'?'नेपाली':'English'}</button><a class="icon-btn" href="#search" aria-label="Search" style="display:grid;place-items:center">🔎</a></div></div></header><nav class="nav"><div class="container">${[['home',L('home')],['category/Nepal',L('nepal')],['category/Politics',L('politics')],['category/Business',L('business')],['category/World',L('world')],['category/Sports',L('sports')],['category/Entertainment',L('entertainment')],['category/Technology',L('technology')],['gallery',L('gallery')],['about',L('about')],['contact',L('contact')]].map(([h,t])=>`<a href="#${h}" class="${active&&h.startsWith(active)?'active':''}">${t}</a>`).join('')}<a class="admin-link" href="#admin">CMS</a></div></nav>${ticker()}`}
function ticker(){const items=published().filter(a=>a.breaking).slice(0,5);return `<div class="ticker"><div class="container"><span class="ticker-label">🔴 ${L('breaking')}</span><div class="ticker-track"><div class="ticker-text">${items.map(a=>esc(articleTitle(a))).join(' &nbsp;&nbsp; • &nbsp;&nbsp; ')||'The Civil Media — latest updates from Nepal and around the world.'}</div></div></div></div>`}
function footer(){const s=data.settings;return `<footer><div class="container footer-grid"><div><div class="footer-logo"><img src="${esc(s.logo)}" alt=""><div><h3 style="margin:0">${esc(s.company)}</h3><small>${esc(s.address)}</small></div></div><p style="color:#aeb9d9;line-height:1.7">Professional digital journalism from Bhaktapur, Nepal.</p></div><div><h3>Sections</h3><a href="#category/Nepal">${L('nepal')}</a><a href="#category/Politics">${L('politics')}</a><a href="#category/Business">${L('business')}</a><a href="#category/Sports">${L('sports')}</a></div><div><h3>Company</h3><a href="#about">${L('about')}</a><a href="#contact">${L('contact')}</a><a href="#admin">Admin CMS</a></div><div><h3>${L('contact')}</h3><a href="mailto:${esc(s.email)}">${esc(s.email)}</a><a href="tel:${esc(s.phone)}">${esc(s.phone)}</a><a>${esc(s.address)}</a></div></div><div class="container" style="padding-bottom:18px">${publicAd('footer')}</div><div class="container copyright">© ${new Date().getFullYear()} ${esc(s.company)}. All rights reserved.</div></footer>`}
function home(){const p=published(), hero=p[0]||seedArticles[0], side=p.slice(1,4), latest=p.slice(1,7);return `${publicHeader('home')}<main><section class="hero"><div class="container hero-grid"><article class="hero-main"><a href="#article/${hero.id}"><img src="${esc(hero.image||fallbackImg)}" alt=""></a><div class="hero-overlay"><span class="eyebrow">${esc(hero.category)}</span><a href="#article/${hero.id}"><h2>${esc(articleTitle(hero))}</h2></a><div class="meta"><span>🕐 ${dateFmt(hero.date)}</span><span>✍️ ${esc(hero.author)}</span></div></div></article><div class="hero-side">${side.map(a=>`<article class="side-story"><a href="#article/${a.id}"><img src="${esc(a.image||fallbackImg)}" alt=""></a><div class="copy"><span class="eyebrow">${esc(a.category)}</span><a href="#article/${a.id}"><h3>${esc(articleTitle(a))}</h3></a><div class="meta">${dateFmt(a.date)}</div></div></article>`).join('')}</div></div></section><section class="section"><div class="container"><div class="section-head"><h2>${L('latest')}</h2><a href="#category/all">${L('allNews')} →</a></div><div class="news-grid">${latest.map(card).join('')}</div></div></section><section class="section"><div class="container category-layout"><div><div class="section-head"><h2>${L('nepal')} & ${L('politics')}</h2></div><div class="list-stack">${p.filter(a=>['Nepal','Politics'].includes(a.category)).slice(0,4).map(listItem).join('')}</div></div><aside class="sidebar"><div class="panel"><h3>${L('trending')}</h3><div class="trending">${p.slice(0,5).map(a=>`<a href="#article/${a.id}">${esc(articleTitle(a))}</a>`).join('')}</div></div>${publicAd('sidebar')}</aside></div></section><section class="section"><div class="container"><div class="section-head"><h2>${L('gallery')}</h2><a href="#gallery">View gallery →</a></div><div class="gallery-grid">${p.filter(a=>['Gallery','Entertainment','Sports','Technology'].includes(a.category)).slice(0,5).map(a=>`<a class="gallery-item" href="#article/${a.id}"><img src="${esc(a.image||fallbackImg)}" alt=""><span>▶ ${esc(articleTitle(a))}</span></a>`).join('')}</div></div></section><section class="section"><div class="container"><div class="newsletter"><div><h2>${L('newsletter')}</h2><p>${L('newsletterSub')}</p></div><form class="newsletter-form" onsubmit="subscribe(event)"><input name="email" type="email" required placeholder="you@example.com"><button class="btn" type="submit">${L('subscribe')}</button></form></div></div></section></main>${footer()}`}
function category(cat){const arr=published().filter(a=>cat==='all'||a.category===cat);return `${publicHeader('category')}<main class="page-wrap"><div class="container category-layout"><div><div class="section-head"><h2>${cat==='all'?L('allNews'):esc(cat)}</h2></div><div class="list-stack">${arr.length?arr.map(listItem).join(''):'<div class="empty">No published articles in this category yet.</div>'}</div></div><aside class="sidebar">${publicAd('sidebar')}<div class="panel"><h3>${L('trending')}</h3><div class="trending">${published().slice(0,5).map(a=>`<a href="#article/${a.id}">${esc(articleTitle(a))}</a>`).join('')}</div></div></aside></div></main>${footer()}`}
function article(id){const a=data.articles.find(x=>x.id===id&&x.status==='published');if(!a)return `${publicHeader()}<main class="page-wrap"><div class="container"><div class="empty">Article not found or not published.</div></div></main>${footer()}`;return `${publicHeader()}<main class="page-wrap"><article class="article-page"><span class="eyebrow">${esc(a.category)}</span><h1>${esc(articleTitle(a))}</h1><p class="lead">${esc(articleExcerpt(a))}</p><div class="meta"><span>🕐 ${dateFmt(a.date)}</span><span>✍️ ${esc(a.author)}</span></div><img class="cover" src="${esc(a.image||fallbackImg)}" alt=""><div class="article-content">${articleContent(a).split(/\n+/).map(p=>`<p>${esc(p)}</p>`).join('')}</div><div class="share-row"><button class="btn secondary sm" onclick="navigator.clipboard?.writeText(location.href);toast('Link copied')">🔗 Copy link</button><a class="btn secondary sm" href="https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(location.href)}" target="_blank">Facebook</a></div></article></main>${footer()}`}
function searchPage(){return `${publicHeader('search')}<main class="search-page"><div class="container"><div class="section-head"><h2>${L('search')}</h2></div><form class="search-box" onsubmit="doSearch(event)"><input id="searchInput" placeholder="Search headline, category or author…" autofocus><button class="btn">${L('search')}</button></form><div id="searchResults"><div class="empty">Type a keyword to search published news.</div></div></div></main>${footer()}`}
function doSearch(e){e.preventDefault();const q=$('#searchInput').value.trim().toLowerCase(), arr=published().filter(a=>[a.titleEn,a.titleNp,a.excerptEn,a.excerptNp,a.category,a.author].join(' ').toLowerCase().includes(q));$('#searchResults').innerHTML=q?(arr.length?`<div class="news-grid">${arr.map(card).join('')}</div>`:'<div class="empty">No matching news found.</div>'):'<div class="empty">Type a keyword to search published news.</div>'}
function galleryPage(){const arr=published().filter(a=>['Gallery','Entertainment','Sports','Technology'].includes(a.category));return `${publicHeader('gallery')}<main class="page-wrap"><div class="container"><div class="section-head"><h2>${L('gallery')}</h2></div><div class="news-grid">${arr.map(card).join('')}</div></div></main>${footer()}`}
function about(){const s=data.settings;return `${publicHeader('about')}<main class="page-wrap"><div class="container"><article class="article-page"><span class="eyebrow">Company</span><h1>${L('about')}</h1><p class="lead">${esc(s.company)} is a digital news portal based in ${esc(s.address)}.</p><div class="article-content"><p>Our goal is to publish timely, accessible reporting across Nepal, politics, business, international affairs, sports, entertainment and technology.</p><p>The Civil Media Private Limited was established in 2026 and is building a modern, bilingual news experience for readers on desktop and mobile.</p></div></article></div></main>${footer()}`}
function contact(){const s=data.settings;return `${publicHeader('contact')}<main class="page-wrap"><div class="container category-layout"><div class="admin-card"><h2>${L('contact')}</h2><form class="form-grid" onsubmit="sendMessage(event)"><div class="field"><label>Name</label><input name="name" required></div><div class="field"><label>Email</label><input type="email" name="email" required></div><div class="field full"><label>Subject</label><input name="subject" required></div><div class="field full"><label>Message</label><textarea name="message" required></textarea></div><div class="field full"><button class="btn">Send message</button></div></form></div><aside class="sidebar"><div class="panel"><h3>${esc(s.company)}</h3><p>📍 ${esc(s.address)}</p><p>📞 ${esc(s.phone)}</p><p>✉️ ${esc(s.email)}</p></div>${publicAd('sidebar')}</aside></div></main>${footer()}`}
function subscribe(e){e.preventDefault();const email=new FormData(e.target).get('email');if(!data.subscribers.includes(email))data.subscribers.push(email);save();e.target.reset();toast('Subscribed successfully')}
function sendMessage(e){e.preventDefault();data.messages.push(Object.fromEntries(new FormData(e.target)));save();e.target.reset();toast('Message saved')}
function setLang(v){lang=v;localStorage.setItem('civilLang',v);render()}
function toast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),2200)}

function isAuthed(){return sessionStorage.getItem(AUTH)==='1'}
function adminLogin(){const s=data.settings;return `<div class="login-wrap"><form class="login-card" onsubmit="login(event)"><img src="${esc(s.logo)}" alt=""><h1>Admin CMS</h1><div class="field"><label>Username</label><input name="username" autocomplete="username" required></div><div class="field"><label>Password</label><input name="password" type="password" autocomplete="current-password" required></div><button class="btn" style="width:100%">Sign in</button><a href="#home" style="display:block;text-align:center;margin-top:14px;color:var(--brand);font-weight:800">← Back to website</a></form></div>`}
function adminSetup(){const s=data.settings;return `<div class="login-wrap"><form class="login-card" onsubmit="createAdmin(event)"><img src="${esc(s.logo)}" alt=""><h1>Create Admin Account</h1><p class="login-note">Create your administrator login before using the CMS.</p><div class="field"><label>Admin username</label><input name="username" autocomplete="username" minlength=3 required></div><div class="field"><label>Admin password</label><input name="password" type="password" autocomplete="new-password" minlength=6 required></div><div class="field"><label>Confirm password</label><input name="confirm" type="password" autocomplete="new-password" minlength=6 required></div><button class="btn" style="width:100%">Create admin account</button><a href="#home" style="display:block;text-align:center;margin-top:14px;color:var(--brand);font-weight:800">← Back to website</a></form></div>`}
function login(e){e.preventDefault();if(!data.credentials)return render();const f=Object.fromEntries(new FormData(e.target));if(f.username===data.credentials.username&&f.password===data.credentials.password){sessionStorage.setItem(AUTH,'1');location.hash='#admin/dashboard';render()}else toast('Invalid username or password')}
function createAdmin(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(f.password!==f.confirm)return toast('Passwords do not match');if(f.password.length<6)return toast('Password must be at least 6 characters');data.credentials={username:f.username,password:f.password};save();sessionStorage.setItem(AUTH,'1');location.hash='#admin/dashboard';render();toast('Admin account created')}
function logout(){sessionStorage.removeItem(AUTH);location.hash='#admin';render()}
const adminNav=[['dashboard','▦','Dashboard'],['articles','📰','Articles'],['editor','＋','Add news'],['ads','📢','Advertisements'],['settings','⚙','Company settings'],['account','🔐','Admin account']];
function adminShell(page,content,title){const s=data.settings;return `<div class="admin-shell"><aside class="admin-sidebar"><div class="admin-brand"><img src="${esc(s.logo)}"><strong>Civil CMS</strong></div><div class="admin-nav">${adminNav.map(([id,ico,label])=>`<button class="${page===id?'active':''}" onclick="location.hash='#admin/${id}'"><span>${ico}</span> <span class="label">${label}</span></button>`).join('')}<button onclick="location.hash='#home'"><span>↗</span> <span class="label">View site</span></button><button onclick="logout()"><span>⇥</span> <span class="label">Logout</span></button></div></aside><main class="admin-main"><div class="admin-top"><div><h1>${title}</h1><div class="meta">${esc(s.company)} • Browser-based CMS</div></div><button class="btn secondary" onclick="location.hash='#home'">View website ↗</button></div>${content}</main></div>`}
function adminDashboard(){const total=data.articles.length,pub=data.articles.filter(a=>a.status==='published').length,draft=data.articles.filter(a=>a.status==='draft').length,arch=data.articles.filter(a=>a.status==='archived').length;return adminShell('dashboard',`<div class="stats"><div class="stat"><b>${total}</b><span>Total articles</span></div><div class="stat"><b>${pub}</b><span>Published</span></div><div class="stat"><b>${draft}</b><span>Drafts</span></div><div class="stat"><b>${arch}</b><span>Archived</span></div></div><div class="admin-card"><div class="admin-top" style="margin-bottom:12px"><h2 style="margin:0">Recent articles</h2><button class="btn sm" onclick="location.hash='#admin/editor'">+ Add news</button></div>${adminTable(data.articles.slice().sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,8))}</div>`,'Dashboard')}
function adminTable(arr){return `<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Title</th><th>Category</th><th>Status</th><th>Published</th><th>Actions</th></tr></thead><tbody>${arr.map(a=>`<tr><td><b>${esc(a.titleEn)}</b><div class="meta">${esc(a.author)}</div></td><td>${esc(a.category)}</td><td><span class="badge ${a.status}">${a.status}</span></td><td>${dateFmt(a.date)}</td><td><div class="actions"><button class="btn secondary sm" onclick="location.hash='#admin/editor/${a.id}'">Edit</button><button class="btn secondary sm" onclick="toggleArchive('${a.id}')">${a.status==='archived'?'Restore':'Archive'}</button><button class="btn danger sm" onclick="deleteArticle('${a.id}')">Delete</button></div></td></tr>`).join('')}</tbody></table></div>`}
function adminArticles(){return adminShell('articles',`<div class="admin-card"><div class="admin-top"><div class="search-box" style="margin:0;flex:1"><input id="adminSearch" placeholder="Search articles…" oninput="filterAdminArticles()"></div><button class="btn" onclick="location.hash='#admin/editor'">+ Add news</button></div><div id="adminArticleTable">${adminTable(data.articles)}</div></div>`,'Articles')}
function filterAdminArticles(){const q=$('#adminSearch').value.toLowerCase();const arr=data.articles.filter(a=>[a.titleEn,a.titleNp,a.category,a.author,a.status].join(' ').toLowerCase().includes(q));$('#adminArticleTable').innerHTML=adminTable(arr)}
function toggleArchive(id){const a=data.articles.find(x=>x.id===id);if(!a)return;a.status=a.status==='archived'?'draft':'archived';save();render();toast('Article status updated')}
function deleteArticle(id){if(confirm('Delete this article permanently?')){data.articles=data.articles.filter(a=>a.id!==id);save();render();toast('Article deleted')}}
function editor(id){const a=id?data.articles.find(x=>x.id===id):null;const v=a||{titleEn:'',titleNp:'',excerptEn:'',excerptNp:'',category:'Nepal',author:'Civil Media Desk',date:new Date().toISOString().slice(0,16),status:'draft',breaking:false,image:'',contentEn:'',contentNp:''};return adminShell('editor',`<form class="admin-card form-grid" onsubmit="saveArticle(event,'${id||''}')"><div class="field"><label>English headline</label><input name="titleEn" value="${esc(v.titleEn)}" required></div><div class="field"><label>Nepali headline</label><input name="titleNp" value="${esc(v.titleNp)}"></div><div class="field"><label>Category</label><select name="category">${['Nepal','Politics','Business','World','Sports','Entertainment','Technology','Gallery'].map(c=>`<option ${v.category===c?'selected':''}>${c}</option>`).join('')}</select></div><div class="field"><label>Author / Byline</label><input name="author" value="${esc(v.author)}" required></div><div class="field"><label>Published date/time</label><input type="datetime-local" name="date" value="${esc(v.date)}" required></div><div class="field"><label>Status</label><select name="status">${['published','draft','archived'].map(s=>`<option value="${s}" ${v.status===s?'selected':''}>${s}</option>`).join('')}</select></div><div class="field full"><label>Image URL</label><input name="image" value="${esc(v.image)}" placeholder="https://… or upload below"></div><div class="field full"><label>Upload image (stored in this browser)</label><input type="file" accept="image/*" id="articleImageUpload"><small class="meta">Large images may exceed browser storage limits.</small></div><div class="field full"><label>English excerpt</label><textarea name="excerptEn" style="min-height:90px">${esc(v.excerptEn)}</textarea></div><div class="field full"><label>Nepali excerpt</label><textarea name="excerptNp" style="min-height:90px">${esc(v.excerptNp)}</textarea></div><div class="field full"><label>English article body</label><textarea name="contentEn">${esc(v.contentEn)}</textarea></div><div class="field full"><label>Nepali article body</label><textarea name="contentNp">${esc(v.contentNp)}</textarea></div><div class="field"><label><input style="width:auto" type="checkbox" name="breaking" ${v.breaking?'checked':''}> Show in Breaking News ticker</label></div><div class="field"><button class="btn" type="submit">${id?'Update article':'Save article'}</button></div></form>`,id?'Edit news':'Add news')}
async function saveArticle(e,id){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));f.breaking=new FormData(e.target).has('breaking');const file=$('#articleImageUpload')?.files?.[0];if(file){f.image=await fileToDataURL(file)} if(id){Object.assign(data.articles.find(a=>a.id===id),f)}else{f.id='a'+Date.now();data.articles.unshift(f)}save();location.hash='#admin/articles';render();toast('Article saved')}
function fileToDataURL(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
function adsList(){const ads=data.ads||[];return adminShell('ads',`<div class="admin-card"><div class="admin-top" style="margin-bottom:12px"><div><h2 style="margin:0">Advertisements</h2><div class="meta">Create and edit the ad spaces shown across the public website.</div></div><button class="btn sm" onclick="location.hash='#admin/ads/new'">+ Add advertisement</button></div>${ads.length?`<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Name</th><th>Placement</th><th>Status</th><th>Destination</th><th>Actions</th></tr></thead><tbody>${ads.map(a=>`<tr><td><b>${esc(a.name)}</b><div class="meta">${esc(a.dimensions||'')}</div></td><td>${esc(a.placement)}</td><td><span class="badge ${a.enabled?'published':'draft'}">${a.enabled?'active':'disabled'}</span></td><td>${a.url?`<a href="${esc(safeUrl(a.url))}" target="_blank" rel="noopener noreferrer">Open ↗</a>`:'—'}</td><td><div class="actions"><button class="btn secondary sm" onclick="location.hash='#admin/ads/${a.id}'">Edit</button><button class="btn secondary sm" onclick="toggleAd('${a.id}')">${a.enabled?'Disable':'Enable'}</button><button class="btn danger sm" onclick="deleteAd('${a.id}')">Delete</button></div></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No advertisements created yet.</div>'}</div>`,'Advertisements')}
function adEditor(id){const a=id&&id!=='new'?data.ads.find(x=>x.id===id):null;const v=a||{name:'',placement:'header',label:'Advertisement',dimensions:'728 × 90',image:'',url:'',alt:'',enabled:true};return adminShell('ads',`<form class="admin-card form-grid" onsubmit="saveAd(event,'${id&&id!=='new'?id:''}')"><div class="field"><label>Advertisement name</label><input name="name" value="${esc(v.name)}" required></div><div class="field"><label>Placement</label><select name="placement"><option value="header" ${v.placement==='header'?'selected':''}>Header banner</option><option value="sidebar" ${v.placement==='sidebar'?'selected':''}>Sidebar rectangle</option><option value="footer" ${v.placement==='footer'?'selected':''}>Footer banner</option></select></div><div class="field"><label>Ad label</label><input name="label" value="${esc(v.label)}"></div><div class="field"><label>Dimensions text</label><input name="dimensions" value="${esc(v.dimensions)}" placeholder="728 × 90"></div><div class="field full"><label>Image URL</label><input name="image" value="${esc(v.image)}" placeholder="https://…"></div><div class="field full"><label>Upload ad image</label><input type="file" accept="image/*" id="adImageUpload"><small class="meta">Uploaded images are stored in this browser.</small></div><div class="field full"><label>Click-through URL</label><input name="url" value="${esc(v.url)}" placeholder="https://advertiser.example.com"></div><div class="field"><label>Image alt text</label><input name="alt" value="${esc(v.alt)}"></div><div class="field"><label><input style="width:auto" type="checkbox" name="enabled" ${v.enabled?'checked':''}> Show this advertisement</label></div><div class="field full"><div class="actions"><button class="btn">${a?'Update advertisement':'Save advertisement'}</button><button type="button" class="btn secondary" onclick="location.hash='#admin/ads'">Cancel</button></div></div></form>` ,a?'Edit advertisement':'Add advertisement')}
async function saveAd(e,id){e.preventDefault();const fd=new FormData(e.target),f=Object.fromEntries(fd);f.enabled=fd.has('enabled');const file=$('#adImageUpload')?.files?.[0];if(file)f.image=await fileToDataURL(file);if(id){Object.assign(data.ads.find(a=>a.id===id),f)}else{f.id='ad'+Date.now();data.ads.unshift(f)}save();location.hash='#admin/ads';render();toast('Advertisement saved')}
function toggleAd(id){const a=data.ads.find(x=>x.id===id);if(!a)return;a.enabled=!a.enabled;save();render();toast(a.enabled?'Advertisement enabled':'Advertisement disabled')}
function deleteAd(id){if(confirm('Delete this advertisement?')){data.ads=data.ads.filter(a=>a.id!==id);save();render();toast('Advertisement deleted')}}
function adminSettings(){const s=data.settings;return adminShell('settings',`<form class="admin-card form-grid" onsubmit="saveSettings(event)"><div class="field"><label>Company name</label><input name="company" value="${esc(s.company)}"></div><div class="field"><label>Tagline</label><input name="tagline" value="${esc(s.tagline)}"></div><div class="field"><label>Address</label><input name="address" value="${esc(s.address)}"></div><div class="field"><label>Email</label><input name="email" value="${esc(s.email)}"></div><div class="field"><label>Phone</label><input name="phone" value="${esc(s.phone)}"></div><div class="field"><label>Logo image URL / data URL</label><input name="logo" value="${esc(s.logo)}"></div><div class="field full"><label>Upload new logo</label><input type="file" accept="image/*" id="logoUpload"></div><div class="field"><label>Brand color</label><input name="brand" type="color" value="${esc(s.brand)}"></div><div class="field"><label>Accent / breaking color</label><input name="accent" type="color" value="${esc(s.accent)}"></div><div class="field"><label>Body font</label><select name="bodyFont">${['Inter','Arial','Georgia','Noto Sans Devanagari'].map(x=>`<option ${s.bodyFont===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Heading font</label><select name="headingFont">${['Playfair Display','Georgia','Inter','Noto Sans Devanagari'].map(x=>`<option ${s.headingFont===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Card / page corner radius</label><input type="range" min="0" max="28" name="radius" value="${esc(s.radius)}"><small class="meta">0 = square, 28 = rounded</small></div><div class="field"><label>Page style</label><select name="layout"><option value="classic" ${s.layout==='classic'?'selected':''}>Classic newsroom</option><option value="soft" ${s.layout==='soft'?'selected':''}>Soft / spacious</option></select></div><div class="field"><label>Facebook URL</label><input name="facebook" value="${esc(s.facebook)}"></div><div class="field"><label>YouTube URL</label><input name="youtube" value="${esc(s.youtube)}"></div><div class="field"><label>Instagram URL</label><input name="instagram" value="${esc(s.instagram)}"></div><div class="field"><label>X URL</label><input name="x" value="${esc(s.x)}"></div><div class="field full"><button class="btn">Save company & design settings</button></div></form>`,'Company & design settings')}
async function saveSettings(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const file=$('#logoUpload')?.files?.[0];if(file)f.logo=await fileToDataURL(file);Object.assign(data.settings,f);save();applyTheme();render();toast('Settings saved')}
function adminAccount(){return adminShell('account',`<form class="admin-card form-grid" onsubmit="saveAccount(event)"><div class="field"><label>Current username</label><input value="${esc(data.credentials.username)}" disabled></div><div class="field"><label>New admin username</label><input name="username" value="${esc(data.credentials.username)}" required></div><div class="field"><label>Current password</label><input type="password" name="current" required></div><div class="field"><label>New password</label><input type="password" name="password" minlength="6" required></div><div class="field full"><button class="btn">Change admin login</button><p class="login-note">Your login is stored in this browser for this prototype. For a public production deployment, use server-side authentication.</p></div></form>`,'Admin account')}
function saveAccount(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(f.current!==data.credentials.password)return toast('Current password is incorrect');data.credentials={username:f.username,password:f.password};save();e.target.reset();toast('Admin login updated')}

function render(){applyTheme();let hash=location.hash.replace(/^#/,'')||'home';if(hash.startsWith('admin')){if(!data.credentials){document.querySelector('#app').innerHTML=adminSetup();return}if(!isAuthed()){document.querySelector('#app').innerHTML=adminLogin();return}const parts=hash.split('/'), page=parts[1]||'dashboard';document.querySelector('#app').innerHTML=page==='dashboard'?adminDashboard():page==='articles'?adminArticles():page==='editor'?editor(parts[2]):page==='ads'?(parts[2]?adEditor(parts[2]):adsList()):page==='settings'?adminSettings():page==='account'?adminAccount():adminDashboard();return}
  const [route,arg]=hash.split('/');document.querySelector('#app').innerHTML=route==='home'?home():route==='category'?category(arg||'all'):route==='article'?article(arg):route==='search'?searchPage():route==='gallery'?galleryPage():route==='about'?about():route==='contact'?contact():home();window.scrollTo(0,0)
}
window.addEventListener('hashchange',render);render();
